name = "plex-blackmagic"
type = "webpack"
account_id = ""
zone_id = ""

routes = [
  "CLOUDFLARE_PLEX_URL/video/:/transcode/universal/decision*", 
  "CLOUDFLARE_PLEX_URL/video/:/transcode/universal/start*", 
  "CLOUDFLARE_PLEX_URL/video/:/transcode/universal/subtitles*"
]
